name: ZeitBlast-UI CI for DEV
on:
  push:
    branches: develop
jobs:
  Build_Node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: NPM Build
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |- 
        npm install
        npm run build
    
    # Upload to Artifacts    
    - uses: actions/upload-artifact@v3
      with:
        name: NODE_FILES
        path: ${{ github.workspace }}

  Deploy_To_DEV_S3:
    runs-on: ubuntu-latest
    needs: Build_Node
    steps:
    - name: Download files from Artifact
      uses: actions/download-artifact@v3
      with:
        name: NODE_FILES
        path: ${{ github.workspace }}
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - run:  aws s3 sync ./ s3://${{ secrets.AWS_DEV_S3_BUCKET }}

  # Invalidate_Cloudfront_Cache:
  #   runs-on: ubuntu-latest
  #   needs: Deploy_To_PROD_S3
  #   steps:  
  #   - name: Invalidate CloudFront
  #     uses: chetan/invalidate-cloudfront-action@v2
  #     env:
  #       DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_PROD }}
  #       PATHS: "/*"
  #       AWS_REGION: "us-east-1"
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
